{% set name = "apprise" %}
{% set version = "1.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apprise-{{ version }}.tar.gz
  sha256: f583667ea35b8899cd46318c6cb26f0faf6a4605b119174c2523a012590c65a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - apprise = apprise.cli:main

requirements:
  host:
    - babel
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - certifi
    - requests
    - requests-oauthlib
    - click >=5.0
    - markdown
    - pyyaml

test:
  source_files:
    - test
  imports:
    - apprise
  commands:
    - pip check
    - apprise --help
    - pytest -vvv --capture=tee-sys test
  requires:
    - pip
    - pytest
    - pytest-mock
    - python {{ python_min }}

about:
  home: https://hub.docker.com/r/caronc/apprise
  dev_url: https://github.com/caronc/apprise
  doc_url: https://github.com/caronc/apprise/wiki
  summary: Push Notifications that work with just about every platform
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
