schema_version: 1

context:
  name: apprise
  version: 1.9.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apprise-${{ version }}.tar.gz
  sha256: 483122aee19a89a7b075ecd48ef11ae37d79744f7aeb450bcf985a9a6c28c988

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - apprise = apprise.cli:main

requirements:
  host:
    - babel
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - certifi
    - requests
    - requests-oauthlib
    - click >=5.0
    - markdown
    - pyyaml

tests:
  - python:
      imports:
        - apprise
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests
    requirements:
      run:
        - pytest
        - pytest-mock
        - python ${{ python_min }}.*
    script:
      - apprise --help
      - pytest -vvv --capture=tee-sys tests

about:
  summary: Push Notifications that work with just about every platform
  license: MIT
  license_file:
    - LICENSE
  homepage: https://hub.docker.com/r/caronc/apprise
  repository: https://github.com/caronc/apprise
  documentation: https://github.com/caronc/apprise/wiki

extra:
  recipe-maintainers:
    - thewchan
